Add basic configuration and info files
kpi-web-guild/django-girls-blog-PetrushynskyiOleksii pull request #5
Opened 2018-01-31 18:44 UTC by PetrushynskyiOleksii

2018-01-31 21:08 UTC, webknjaz requested changes
Why did you use that wording in commit messages? I can see that you create files from commit metadata, you shouldn't repeat obvious things in commit message. It's an implementation detail. Your goal is to inform history reader about your intention, of what is the effect of the commit on the project, what you are trying to achieve.

2018-01-31 21:08 UTC, webknjaz commented on LICENSE
> +Copyright (c) 2018 Fullname
Fullname? Is that how you call yourself?

2018-02-01 21:42 UTC, webknjaz requested changes
Please refer the issue you are solving in the PR description. (ref. https://help.github.com/articles/closing-issues-using-keywords/)

2018-02-02 09:47 UTC, PetrushynskyiOleksii commented
@webknjaz done.

2018-02-02 13:04 UTC, webknjaz approved these changes

2018-02-03 07:40 UTC, merged